/**
 * Jurisdiction registry.
 * Every country is a self-contained rule module. The payroll engine never hard-codes
 * a country; it reads this registry (merged with any overrides saved in Compliance settings).
 *
 * Rates below are a starting configuration for the 2026 payroll year. They are editable at
 * runtime and MUST be verified against current statutes with local counsel before live use.
 */

export const COUNTRIES = {
  US: {
    code: 'US',
    name: 'United States',
    region: 'North America',
    currency: { code: 'USD', symbol: '$', decimals: 2, locale: 'en-US' },
    payFrequency: 'biweekly',
    workWeekHours: 40,
    weekend: ['Sat', 'Sun'],
    overtime: {
      threshold: 40, multiplier: 1.5, basis: 'weekly', law: 'FLSA §7',
      rounding: { increment: 15, rule: 'nearest' }, // FLSA-permitted 15-min "7-minute rule" rounding
      dailyCap: null, weeklyCap: null, requiresPriorApproval: false,
    },
    leave: {
      annual: { accrualDaysPerYear: 15, accrualMethod: 'per-pay-period', carryoverCapDays: 5, unit: 'PTO (discretionary; no federal mandate)' },
      sick: { daysPerYear: null, note: 'No federal mandate; state/local sick leave laws vary (e.g., CA, NY, WA)' },
      public: { daysPerYear: 11, note: 'Federal holidays; employer discretion for paid status' },
      maternity: { weeksPaid: 0, weeksUnpaid: 12, note: 'FMLA unpaid, 12 weeks, employers 50+ employees' },
      paternity: { weeksPaid: 0, weeksUnpaid: 12, note: 'FMLA unpaid, same eligibility as maternity' },
    },
    minimumWage: { amount: 7.25, unit: 'hour', note: 'Federal floor; states may set higher' },
    incomeTax: {
      enabled: true,
      authority: 'IRS',
      standardDeduction: 16100,
      brackets: [
        { upTo: 12400, rate: 0.10 },
        { upTo: 50400, rate: 0.12 },
        { upTo: 105700, rate: 0.22 },
        { upTo: 201775, rate: 0.24 },
        { upTo: 256225, rate: 0.32 },
        { upTo: 640600, rate: 0.35 },
        { upTo: null, rate: 0.37 },
      ],
      stateTax: { default: 0.0, byState: { CA: 0.06, NY: 0.055, TX: 0, FL: 0, WA: 0, IL: 0.0495, MA: 0.05 } },
    },
    socialSecurity: {
      name: 'FICA',
      employee: [
        { id: 'ss', label: 'Social Security', rate: 0.062, wageBase: 184500 },
        { id: 'medicare', label: 'Medicare', rate: 0.0145, wageBase: null },
        { id: 'medicare_add', label: 'Additional Medicare', rate: 0.009, above: 200000 },
      ],
      employer: [
        { id: 'ss', label: 'Social Security', rate: 0.062, wageBase: 184500 },
        { id: 'medicare', label: 'Medicare', rate: 0.0145, wageBase: null },
        { id: 'futa', label: 'FUTA', rate: 0.006, wageBase: 7000 },
      ],
      appliesTo: 'all',
    },
    endOfService: { enabled: false },
    wageProtection: { system: null, required: false },
    compliance: [
      { id: 'w4', label: 'Form W-4 on file for every employee', severity: 'high' },
      { id: 'i9', label: 'Form I-9 employment eligibility verified', severity: 'high' },
      { id: 'flsa_ot', label: 'Non-exempt overtime paid at 1.5× beyond 40 h/week', severity: 'high' },
      { id: 'w2', label: 'W-2 issued by 31 January', severity: 'medium' },
      { id: 'pay_stub', label: 'Itemised pay statement provided (state rules vary)', severity: 'medium' },
    ],
  },

  AE: {
    code: 'AE',
    name: 'United Arab Emirates',
    region: 'Middle East',
    currency: { code: 'AED', symbol: 'AED', decimals: 2, locale: 'en-AE' },
    payFrequency: 'monthly',
    workWeekHours: 48,
    weekend: ['Sat', 'Sun'],
    overtime: { threshold: 8, multiplier: 1.25, nightMultiplier: 1.5, basis: 'daily', law: 'Federal Decree-Law 33/2021 Art. 19', rounding: { increment: 30, rule: 'up' }, dailyCap: 2, weeklyCap: null, requiresPriorApproval: true },
    leave: {
      annual: { accrualDaysPerYear: 30, accrualMethod: 'monthly', proRata: '2 days/month for 6–12 months tenure', unit: 'calendar days' },
      sick: { daysPerYear: 90, tiers: [{ days: 15, pay: 1 }, { days: 30, pay: 0.5 }, { days: 45, pay: 0 }], note: 'Not payable in first 3 months of service' },
      public: { daysPerYear: 14 },
      maternity: { weeksPaid: 6.4, weeksUnpaid: 0, note: '45 days full pay + 15 days half pay (Art. 30)' },
      paternity: { weeksPaid: 0.7, weeksUnpaid: 0, note: '5 working days' },
    },
    minimumWage: { amount: null, unit: 'month', note: 'No statutory minimum; MoHRE guidance applies' },
    incomeTax: { enabled: false, authority: 'FTA', note: 'No personal income tax' },
    socialSecurity: {
      name: 'GPSSA',
      employee: [{ id: 'gpssa', label: 'GPSSA pension', rate: 0.05, wageBase: 70000, floor: 1000 }],
      employer: [{ id: 'gpssa', label: 'GPSSA pension', rate: 0.125, wageBase: 70000, floor: 1000 }],
      appliesTo: 'nationals',
      note: 'UAE nationals only; monthly contributory salary between AED 1,000 and 70,000',
    },
    endOfService: {
      enabled: true,
      basis: 'basic',
      tiers: [{ uptoYears: 5, daysPerYear: 21 }, { uptoYears: null, daysPerYear: 30 }],
      capMonths: 24,
      minServiceYears: 1,
      law: 'Federal Decree-Law 33/2021 Art. 51',
    },
    wageProtection: { system: 'WPS', required: true, payWithinDays: 15, fileFormat: 'SIF' },
    compliance: [
      { id: 'wps', label: 'Salaries paid through WPS within 15 days of due date', severity: 'high' },
      { id: 'iban', label: 'Valid IBAN registered for every employee', severity: 'high' },
      { id: 'emirates_id', label: 'Emirates ID and labour card on file', severity: 'high' },
      { id: 'eosb_accrual', label: 'End-of-service gratuity accrued monthly', severity: 'medium' },
      { id: 'ot_cap', label: 'Overtime does not exceed 2 h/day', severity: 'medium' },
    ],
  },

  SA: {
    code: 'SA',
    name: 'Saudi Arabia',
    region: 'Middle East',
    currency: { code: 'SAR', symbol: 'SAR', decimals: 2, locale: 'en-SA' },
    payFrequency: 'monthly',
    workWeekHours: 48,
    weekend: ['Fri', 'Sat'],
    overtime: { threshold: 8, multiplier: 1.5, basis: 'daily', law: 'Labour Law Art. 107', rounding: { increment: 30, rule: 'up' }, dailyCap: 2, weeklyCap: null, requiresPriorApproval: true },
    leave: {
      annual: { accrualDaysPerYear: 21, tiers: [{ afterYears: 5, daysPerYear: 30 }], accrualMethod: 'monthly', unit: 'calendar days' },
      sick: { daysPerYear: 120, tiers: [{ days: 30, pay: 1 }, { days: 60, pay: 0.75 }, { days: 30, pay: 0 }] },
      public: { daysPerYear: 10 },
      maternity: { weeksPaid: 10, weeksUnpaid: 0, note: '10 weeks, up to 4 weeks before due date' },
      paternity: { weeksPaid: 0, weeksUnpaid: 0, note: 'No statutory paternity leave' },
    },
    minimumWage: { amount: 4000, unit: 'month', note: 'Applies to Saudi nationals for Nitaqat counting' },
    incomeTax: { enabled: false, authority: 'ZATCA', note: 'No personal income tax' },
    socialSecurity: {
      name: 'GOSI',
      employee: [
        { id: 'annuity', label: 'GOSI annuities', rate: 0.09, wageBase: 45000, floor: 1500 },
        { id: 'saned', label: 'SANED unemployment', rate: 0.0075, wageBase: 45000, floor: 1500 },
      ],
      employer: [
        { id: 'annuity', label: 'GOSI annuities', rate: 0.09, wageBase: 45000, floor: 1500 },
        { id: 'saned', label: 'SANED unemployment', rate: 0.0075, wageBase: 45000, floor: 1500 },
        { id: 'oh', label: 'Occupational hazards', rate: 0.02, wageBase: 45000, floor: 1500 },
      ],
      expatEmployer: [{ id: 'oh', label: 'Occupational hazards', rate: 0.02, wageBase: 45000, floor: 1500 }],
      appliesTo: 'nationals',
      note: 'Annuity rates rise gradually for new entrants under the 2024 reform — review yearly',
    },
    endOfService: {
      enabled: true,
      basis: 'gross',
      tiers: [{ uptoYears: 5, daysPerYear: 15 }, { uptoYears: null, daysPerYear: 30 }],
      capMonths: null,
      minServiceYears: 2,
      law: 'Labour Law Art. 84',
    },
    wageProtection: { system: 'WPS (Mudad)', required: true, payWithinDays: 10, fileFormat: 'Mudad' },
    compliance: [
      { id: 'mudad', label: 'Wages uploaded to Mudad/WPS each month', severity: 'high' },
      { id: 'gosi_reg', label: 'All employees registered with GOSI', severity: 'high' },
      { id: 'iqama', label: 'Valid Iqama for expatriate staff', severity: 'high' },
      { id: 'nitaqat', label: 'Saudisation ratio within Nitaqat band', severity: 'medium' },
      { id: 'contract_qiwa', label: 'Contracts authenticated in Qiwa', severity: 'medium' },
    ],
  },

  QA: {
    code: 'QA',
    name: 'Qatar',
    region: 'Middle East',
    currency: { code: 'QAR', symbol: 'QAR', decimals: 2, locale: 'en-QA' },
    payFrequency: 'monthly',
    workWeekHours: 48,
    weekend: ['Fri', 'Sat'],
    overtime: { threshold: 8, multiplier: 1.25, nightMultiplier: 1.5, basis: 'daily', law: 'Law 14/2004 Art. 74', rounding: { increment: 30, rule: 'up' }, dailyCap: 2, weeklyCap: null, requiresPriorApproval: true },
    leave: {
      annual: { accrualDaysPerYear: 21, tiers: [{ afterYears: 5, daysPerYear: 28 }], accrualMethod: 'monthly', unit: 'calendar days' },
      sick: { daysPerYear: 42, tiers: [{ days: 14, pay: 1 }, { days: 28, pay: 0.5 }] },
      public: { daysPerYear: 12 },
      maternity: { weeksPaid: 7.1, weeksUnpaid: 0, note: '50 days full pay' },
      paternity: { weeksPaid: 0, weeksUnpaid: 0, note: 'No statutory paternity leave' },
    },
    minimumWage: { amount: 1000, unit: 'month', note: 'Plus QAR 300 food and QAR 500 housing if not provided' },
    incomeTax: { enabled: false, authority: 'GTA', note: 'No personal income tax' },
    socialSecurity: {
      name: 'GRSIA',
      employee: [{ id: 'grsia', label: 'GRSIA pension', rate: 0.07, wageBase: 100000 }],
      employer: [{ id: 'grsia', label: 'GRSIA pension', rate: 0.14, wageBase: 100000 }],
      appliesTo: 'nationals',
    },
    endOfService: {
      enabled: true,
      basis: 'basic',
      tiers: [{ uptoYears: null, daysPerYear: 21 }],
      capMonths: null,
      minServiceYears: 1,
      law: 'Law 14/2004 Art. 54',
    },
    wageProtection: { system: 'WPS', required: true, payWithinDays: 7, fileFormat: 'SIF' },
    compliance: [
      { id: 'wps', label: 'Salaries paid through WPS within 7 days', severity: 'high' },
      { id: 'qid', label: 'Qatar ID on file', severity: 'high' },
      { id: 'min_wage', label: 'Basic wage at or above QAR 1,000', severity: 'high' },
      { id: 'eosb_accrual', label: 'Gratuity accrued at 3 weeks per year', severity: 'medium' },
    ],
  },

  KW: {
    code: 'KW',
    name: 'Kuwait',
    region: 'Middle East',
    currency: { code: 'KWD', symbol: 'KWD', decimals: 3, locale: 'en-KW' },
    payFrequency: 'monthly',
    workWeekHours: 48,
    weekend: ['Fri', 'Sat'],
    overtime: { threshold: 8, multiplier: 1.25, basis: 'daily', law: 'Law 6/2010 Art. 66', rounding: { increment: 30, rule: 'up' }, dailyCap: 2, weeklyCap: null, requiresPriorApproval: true },
    leave: {
      annual: { accrualDaysPerYear: 30, accrualMethod: 'monthly', unit: 'calendar days' },
      sick: { daysPerYear: 70, tiers: [{ days: 15, pay: 1 }, { days: 10, pay: 0.75 }, { days: 45, pay: 0 }] },
      public: { daysPerYear: 13 },
      maternity: { weeksPaid: 10, weeksUnpaid: 0, note: '70 calendar days' },
      paternity: { weeksPaid: 0, weeksUnpaid: 0, note: 'No statutory paternity leave' },
    },
    minimumWage: { amount: 75, unit: 'month' },
    incomeTax: { enabled: false, authority: 'MoF', note: 'No personal income tax' },
    socialSecurity: {
      name: 'PIFSS',
      employee: [{ id: 'pifss', label: 'PIFSS pension', rate: 0.115, wageBase: 2750 }],
      employer: [{ id: 'pifss', label: 'PIFSS pension', rate: 0.115, wageBase: 2750 }],
      appliesTo: 'nationals',
    },
    endOfService: {
      enabled: true,
      basis: 'gross',
      tiers: [{ uptoYears: 5, daysPerYear: 15 }, { uptoYears: null, daysPerYear: 30 }],
      capMonths: 18,
      minServiceYears: 0,
      law: 'Law 6/2010 Art. 51',
    },
    wageProtection: { system: 'Bank transfer (MoSAL)', required: true, payWithinDays: 7 },
    compliance: [
      { id: 'mosal', label: 'Salaries transferred to local bank accounts', severity: 'high' },
      { id: 'civil_id', label: 'Civil ID on file', severity: 'high' },
      { id: 'indemnity', label: 'Indemnity accrued monthly', severity: 'medium' },
    ],
  },

  BH: {
    code: 'BH',
    name: 'Bahrain',
    region: 'Middle East',
    currency: { code: 'BHD', symbol: 'BHD', decimals: 3, locale: 'en-BH' },
    payFrequency: 'monthly',
    workWeekHours: 48,
    weekend: ['Fri', 'Sat'],
    overtime: { threshold: 8, multiplier: 1.25, nightMultiplier: 1.5, basis: 'daily', law: 'Law 36/2012 Art. 54', rounding: { increment: 30, rule: 'up' }, dailyCap: 2, weeklyCap: null, requiresPriorApproval: true },
    leave: {
      annual: { accrualDaysPerYear: 30, accrualMethod: 'monthly', unit: 'calendar days' },
      sick: { daysPerYear: 55, tiers: [{ days: 15, pay: 1 }, { days: 20, pay: 0.5 }, { days: 20, pay: 0 }] },
      public: { daysPerYear: 12 },
      maternity: { weeksPaid: 10.7, weeksUnpaid: 0, note: '75 days full pay (2019 amendment)' },
      paternity: { weeksPaid: 0.3, weeksUnpaid: 0, note: '1 working day' },
    },
    minimumWage: { amount: null, unit: 'month', note: 'No statutory minimum for private sector' },
    incomeTax: { enabled: false, authority: 'NBR', note: 'No personal income tax' },
    socialSecurity: {
      name: 'SIO',
      employee: [
        { id: 'sio', label: 'SIO pension', rate: 0.08, wageBase: 4000 },
        { id: 'unemp', label: 'Unemployment insurance', rate: 0.01, wageBase: null },
      ],
      employer: [
        { id: 'sio', label: 'SIO pension', rate: 0.15, wageBase: 4000 },
        { id: 'unemp', label: 'Unemployment insurance', rate: 0.01, wageBase: null },
      ],
      expatEmployer: [
        { id: 'sio_inj', label: 'SIO injury', rate: 0.03, wageBase: 4000 },
        { id: 'unemp', label: 'Unemployment insurance', rate: 0.01, wageBase: null },
      ],
      appliesTo: 'nationals',
      note: 'Employer pension share for Bahrainis steps up 1% each January until 20%',
    },
    endOfService: {
      enabled: true,
      basis: 'gross',
      tiers: [{ uptoYears: 3, daysPerYear: 15 }, { uptoYears: null, daysPerYear: 30 }],
      capMonths: null,
      minServiceYears: 0,
      law: 'Law 36/2012 Art. 116 (expatriates via SIO from 2024)',
    },
    wageProtection: { system: 'WPS (LMRA)', required: true, payWithinDays: 7 },
    compliance: [
      { id: 'lmra', label: 'Wages reported through LMRA WPS', severity: 'high' },
      { id: 'cpr', label: 'CPR on file', severity: 'high' },
      { id: 'bahrainisation', label: 'Bahrainisation ratio met', severity: 'medium' },
    ],
  },

  OM: {
    code: 'OM',
    name: 'Oman',
    region: 'Middle East',
    currency: { code: 'OMR', symbol: 'OMR', decimals: 3, locale: 'en-OM' },
    payFrequency: 'monthly',
    workWeekHours: 45,
    weekend: ['Fri', 'Sat'],
    overtime: { threshold: 9, multiplier: 1.25, nightMultiplier: 1.5, basis: 'daily', law: 'Royal Decree 53/2023 Art. 70', rounding: { increment: 30, rule: 'up' }, dailyCap: 2, weeklyCap: null, requiresPriorApproval: true },
    leave: {
      annual: { accrualDaysPerYear: 30, accrualMethod: 'monthly', unit: 'calendar days' },
      sick: { daysPerYear: 70, tiers: [{ days: 21, pay: 1 }, { days: 21, pay: 0.5 }, { days: 28, pay: 0 }] },
      public: { daysPerYear: 12 },
      maternity: { weeksPaid: 7.1, weeksUnpaid: 0, note: '50 calendar days' },
      paternity: { weeksPaid: 0.3, weeksUnpaid: 0, note: '1 week' },
    },
    minimumWage: { amount: 325, unit: 'month', note: 'Omani nationals; OMR 325 basic + allowances' },
    incomeTax: {
      enabled: false,
      authority: 'OTA',
      note: 'Personal income tax of 5% on income above OMR 42,000 takes effect 1 Jan 2028 — engine ready, currently off',
      scheduled: { effective: '2028-01-01', rate: 0.05, threshold: 42000 },
    },
    socialSecurity: {
      name: 'SPF',
      employee: [
        { id: 'spf', label: 'SPF pension', rate: 0.07, wageBase: 3000 },
        { id: 'jobsec', label: 'Job security', rate: 0.01, wageBase: null },
      ],
      employer: [
        { id: 'spf', label: 'SPF pension', rate: 0.105, wageBase: 3000 },
        { id: 'inj', label: 'Injury insurance', rate: 0.01, wageBase: null },
        { id: 'jobsec', label: 'Job security', rate: 0.01, wageBase: null },
      ],
      appliesTo: 'nationals',
    },
    endOfService: {
      enabled: true,
      basis: 'basic',
      tiers: [{ uptoYears: null, daysPerYear: 30 }],
      capMonths: null,
      minServiceYears: 1,
      law: 'Royal Decree 53/2023 Art. 61 (one month basic per year)',
    },
    wageProtection: { system: 'WPS (MoL)', required: true, payWithinDays: 7 },
    compliance: [
      { id: 'wps', label: 'Wages paid through WPS within 7 days', severity: 'high' },
      { id: 'omanisation', label: 'Omanisation quota met', severity: 'medium' },
      { id: 'eosb_accrual', label: 'End-of-service accrued monthly', severity: 'medium' },
    ],
  },
};

/** USD-based reference FX rates (mid-market, editable in Settings). */
export const FX_RATES = { USD: 1, AED: 3.6725, SAR: 3.75, QAR: 3.64, KWD: 0.3075, BHD: 0.376, OMR: 0.3845, EUR: 0.92, GBP: 0.78, INR: 83.5 };

export const CURRENCIES = {
  USD: { name: 'US dollar', symbol: '$', decimals: 2 },
  AED: { name: 'UAE dirham', symbol: 'AED', decimals: 2 },
  SAR: { name: 'Saudi riyal', symbol: 'SAR', decimals: 2 },
  QAR: { name: 'Qatari riyal', symbol: 'QAR', decimals: 2 },
  KWD: { name: 'Kuwaiti dinar', symbol: 'KWD', decimals: 3 },
  BHD: { name: 'Bahraini dinar', symbol: 'BHD', decimals: 3 },
  OMR: { name: 'Omani rial', symbol: 'OMR', decimals: 3 },
  EUR: { name: 'Euro', symbol: '€', decimals: 2 },
  GBP: { name: 'Pound sterling', symbol: '£', decimals: 2 },
  INR: { name: 'Indian rupee', symbol: '₹', decimals: 2 },
};
